version: "3"

services:

  server:
    build: ./server
    restart: on-failure
    depends_on:
      - db
    environment:
      - "db:uri=mongodb://db/docker"
    networks:
      - traefik-net
      - db-net
    labels:
      - traefik.docker.network=traefik-net
      - traefik.frontend.rule=Host:api.docker-example.local
      - traefik.port=3000


  client:
    build: ./client
    restart: on-failure
    depends_on:
      - server
    networks:
      - traefik-net
    labels:
      - traefik.frontend.rule=Host:docker-example.local
      - traefik.port=4000


  db:
    image: mongo
    restart: on-failure
    networks:
      - db-net
    labels:
      - traefik.enable=false


  reverse-proxy:
    image: traefik
    restart: always
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./proxy/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      traefik-net:
        aliases:
          - api.docker-example.local
    labels:
      - traefik.frontend.rule=Host:monit.docker-example.local
      - traefik.port=8080


networks:
  traefik-net:
    external: true
  db-net:
