debug = false

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
    address = ":80"

[api]

[docker]
    endpoint = "unix:///var/run/docker.sock"
    domain = "docker-example.local"
    watch = true